{% set name = "lovely-tensors" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: faf5d1c675d517e4e736131feeb28efe9d7a2125dbe5e6829675d590524ebc59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch
    - lovely-numpy >=0.2.8

test:
  imports:
    - lovely_tensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-tensors
  summary: ❤️ Lovely Tensors
  license: MIT
  license_file: LICENSE
  description: |2

    PyPI: [https://pypi.org/project/lovely-tensors/](https://pypi.org/project/lovely-tensors/)

  dev_url: https://github.com/xl0/lovely-tensors
  doc_url: https://xl0.github.io/lovely-tensors/

extra:
  recipe-maintainers:
    - sugatoray
    - xl0
