{% set name = "lovely-tensors" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lovely-tensors-{{ version }}.tar.gz
  sha256: db8428876774fcc6e64f7224eef4621568c7e2e95e4117ba553b9b017f6184f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch
    - pillow
    - fastcore
    - numpy
    - ipython
    - matplotlib-base

test:
  imports:
    - lovely_tensors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-tensors
  summary: ❤️ Lovely Tensors
  license: MIT
  license_file: LICENSE
  description: |4

    PyPI: [https://pypi.org/project/lovely-tensors/](https://pypi.org/project/lovely-tensors/)

  dev_url: https://github.com/xl0/lovely-tensors
  doc_url: https://xl0.github.io/lovely-tensors/

extra:
  recipe-maintainers:
    - sugatoray
